SCANNING_GOTO_VELOCITY = 0.5
VERTICAL_DELTA = 0.1
ROTATION_VELOCITY = 15  # DEGREE PER SECOND
SENSOR_READING_FREQUENCY = 20
SENSOR_READING_INTERVAL = 1000 / SENSOR_READING_FREQUENCY
# Enable plotting of down sensor
PLOT_SENSOR_DOWN = False
# Set the sensor threshold (in mm)
SENSOR_TH = 2000
